title: Anwar Alam # your name (or website title) here
logo: "/images/anwar alam.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Android Developer 
  <br><br>
  Currently Learning Flutter 
  <br><br>
  <a href="https://www.linkedin.com/in/newgalaxian/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
